---
# vim: filetype=yaml.ansible
# --------------------------

- name: Mark the user-config role as IN PROGRESS
  shell: echo 'IN PROGRESS' > /etc/.setup/user-config

# -----------------------------------------------------------------------------

- name: Generate salted password hash for {{ username }}
  shell: echo "{{ user_password_plain }}" | mkpasswd --method=yescrypt --stdin
  register: mkpasswd_reg

- name: Store the salted password hash into variable
  set_fact:
    user_password_hash: "{{ mkpasswd_reg.stdout }}"

# -----------------------------------------------------------------------------

- name: Create a primary group for {{ username }} [{{ group_id }}]
  group:
    gid:    "{{ group_id }}"
    name:   "{{ username }}"
    state:  present

- name: Create a new user [{{ username }}] with user ID == {{ user_id }}
  user:
    comment:  "{{ display_name }}"
    name:     "{{ username }}"
    uid:      "{{ user_id }}"
    group:    "{{ username }}"
    groups:   "{{ groups_membership }}"
    shell:    "{{ user_login_shell }}"
    password: "{{ user_password_hash }}"

    update_password:  on_create
    append:           yes

# This one is needed to be able to run Toolboxes on Silverblue:
- name: Create additional subuid and subgid to run rootless containers
  command:
    argv:
      - usermod
      - --add-subuids
      - "{{ subuid_start }}-{{ subuid_start + subuid_range }}"
      - --add-subgids
      - "{{ subgid_start }}-{{ subgid_start + subgid_range }}"
      - "{{ username }}"

# -----------------------------------------------------------------------------

- name: Mark the user-config role as DONE
  shell: echo 'DONE' > /etc/.setup/user-config

