---
# vim: filetype=yaml.ansible
# --------------------------
# Configuration (variables) for Normandy-SR3 [Desktop]

hostname_FQDN:  Normandy-SR3.deekej.io

# ---| Partitions Configuration |----------------------------------------------
NTFS_mounts:  true

NTFS_mount_points:
  - device:       /dev/sda1
    mount_point:  /mnt/Downloads

  - device:       /dev/sdb2
    mount_point:  /mnt/Storage

  - device:       /dev/sdc1
    mount_point:  /mnt/Scratch

# ---| DNF repos configuration |-----------------------------------------------
nVidia_drivers: true

# ---| Layered packages configuration |----------------------------------------
install_drivers:                true
drivers_nVidia_suspend_fix:     true
drivers_nVidia_powerd_service:  false

drivers_nVidia_extra:
  - nvidia-driver-NvFBCOpenGL
  - nvenc

# ---| Flatpak packages configuration |----------------------------------------
# NOTE: In case of failure of flatpak packages installation, you might
#       (most likely) need to specify which branch to use - after the slashes: //

# NOTE: Flatpak for nVidia drivers is pulled in automatically for each version.
flatpak_packages_extra_drivers:
  - org.freedesktop.Platform.GL.default//21.08

flatpak_packages_extra_user:
  - com.spotify.Client                    # Music Streamer
  - org.soundconverter.SoundConverter     # Sound Converter
  - org.gnome.EasyTAG                     # ID3 editor for MP3
  - org.gimp.GIMP                         # Graphical Editor
  - org.inkscape.Inkscape                 # Vector Editor
  - org.telegram.desktop                  # Instant Messaging App
  - org.qbittorrent.qBittorrent           # BitTorrent Client

# ---| System configuration |--------------------------------------------------
laptop_config:        false
redhat_work_config:   true
#CUPS_on_LDAP_server:  false
